-- 3.1. Tạo database
CREATE DATABASE QLHH;

--3.2. Tạo bảng
USE QLHH;

CREATE TABLE KHACHHANG
(
	MAKHACHHANG VARCHAR(10) NOT NULL,
	TENCONGTY NVARCHAR(100) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL,
	FAX VARCHAR(20)
);

CREATE TABLE NHANVIEN
(
	MANHANVIEN VARCHAR(10) NOT NULL,
	HO NVARCHAR(30) NOT NULL,
	TEN NVARCHAR(10) NOT NULL,
	NGAYSINH DATE NOT NULL,
	NGAYLAMVIEC DATE NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	DIENTHOAI VARCHAR(20),
	LUONGCOBAN MONEY NOT NULL,
	PHUCAP MONEY NOT NULL
);

CREATE TABLE NHACUNGCAP
(
	MACONGTY VARCHAR(10) NOT NULL,
	TENCONGTY NVARCHAR(100) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(20) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL,
	FAX VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL
);

CREATE TABLE MATHANG
(
	MAHANG VARCHAR(10) NOT NULL,
	TENHANG NVARCHAR(100) NOT NULL,
	MACONGTY VARCHAR(10) NOT NULL,
	MALOAIHANG VARCHAR(10) NOT NULL,
	SOLUONG DECIMAL(10,2) NOT NULL,
	DONVITINH NVARCHAR(20) NOT NULL,
	GIAHANG MONEY NOT NULL
);

CREATE TABLE LOAIHANG
(
	MALOAIHANG VARCHAR(10) NOT NULL,
	TENLOAIHANG NVARCHAR(100) NOT NULL
);

CREATE TABLE DONDATHANG
(
	SOHOADON VARCHAR(10) NOT NULL,
	MAKHACHHANG VARCHAR(10) NOT NULL,
	MANHANVIEN VARCHAR(10) NOT NULL,
	NGAYDATHANG DATETIME,
	NGAYGIAOHANG DATETIME,
	NGAYCHUYENHANG DATETIME,
	NOIGIAOHANG NVARCHAR(100),
);

CREATE TABLE CTDATHANG
(
	SOHOADON VARCHAR(10) NOT NULL,
	MAHANG VARCHAR(10) NOT NULL,
	GIABAN MONEY NOT NULL,
	SOLUONG DECIMAL(10,2) NOT NULL,
	MUCGIAMGIA DECIMAL(4,2) NOT NULL
);

-- 3.3. Tạo Primary Key và Foreign Key

-- a. Tạo Primary Key

ALTER TABLE CTDATHANG
ADD CONSTRAINT ctdathang_pk PRIMARY KEY (SOHOADON, MAHANG);

ALTER TABLE KHACHHANG
ADD CONSTRAINT khachhang_pk PRIMARY KEY (MAKHACHHANG);

ALTER TABLE NHANVIEN
ADD CONSTRAINT nhanvien_pk PRIMARY KEY (MANHANVIEN);

ALTER TABLE MATHANG
ADD CONSTRAINT mathang_pk PRIMARY KEY (MAHANG);

ALTER TABLE DONDATHANG
ADD CONSTRAINT dondathang_pk PRIMARY KEY (SOHOADON);

ALTER TABLE LOAIHANG
ADD CONSTRAINT loaihang_pk PRIMARY KEY (MALOAIHANG);

ALTER TABLE NHACUNGCAP
ADD CONSTRAINT nhacungcap_pk PRIMARY KEY (MACONGTY);

-- b. Tạo Foreign Key

ALTER TABLE CTDATHANG
ADD CONSTRAINT ctdathang_sohoadon_fk FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG (SOHOADON),
	CONSTRAINT ctdathang_mahang_fk FOREIGN KEY (MAHANG) REFERENCES MATHANG (MAHANG);

ALTER TABLE DONDATHANG
ADD CONSTRAINT dondathang_makhachhang_fk FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG (MAKHACHHANG),
	CONSTRAINT dondathang_manhanvien_fk FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN (MANHANVIEN);

ALTER TABLE MATHANG
ADD CONSTRAINT mathang_macongty_fk FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP (MACONGTY),
	CONSTRAINT mathang_maloaihang_fk FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG (MALOAIHANG);

-- 3.4. Tạo dữ liệu