-- 2.1. Tạo database QLDA
CREATE DATABASE QLDA;

-- 2.2. Tạo bảng

USE QLDA;

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(5) NOT NULL,
	HONV NVARCHAR(20) NOT NULL,
	TENLOT NVARCHAR(20) NOT NULL,
	TENNV NVARCHAR(10) NOT NULL,
	NGAYSINH DATE NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	PHAI VARCHAR(5) NOT NULL,
	LUONG DECIMAL(10,2) NOT NULL,
	MAPB VARCHAR(5) NOT NULL
);

CREATE TABLE THANNHAN
(
	MANV VARCHAR(5) NOT NULL,
	TENTN NVARCHAR(30) NOT NULL,
	PHAI VARCHAR(5) NOT NULL,
	NGAYSINH DATE NOT NULL,
	QUANHE NVARCHAR(20) NOT NULL,
);

CREATE TABLE DEAN
(
	MADA VARCHAR(5) NOT NULL,
	TENDA NVARCHAR(50) NOT NULL,
	DDIEM_DA NVARCHAR(100) NOT NULL,
	MAPB VARCHAR(5) NOT NULL
);

CREATE TABLE DDIEMPB
(
	MAPB VARCHAR(5) NOT NULL,
	DIADIEM NVARCHAR(100) NOT NULL
);

CREATE TABLE PHANCONG
(
	MANV VARCHAR(5) NOT NULL,
	MADA VARCHAR(5) NOT NULL,
	THOIGIAN DECIMAL(5,1) NOT NULL
);

CREATE TABLE PHONGBAN
(
	MAPB VARCHAR(5) NOT NULL,
	TENPB NVARCHAR(50) NOT NULL,
	TRUONGPHONG VARCHAR(5) NOT NULL,
	NG_NHANCHUC DATE NOT NULL
);

-- 2.3. Tạo khóa chính và khóa ngoại

-- a. Tạo khóa chính

ALTER TABLE NHANVIEN
ADD CONSTRAINT nhanvien_pk PRIMARY KEY (MANV);

ALTER TABLE PHONGBAN
ADD CONSTRAINT phongban_pk PRIMARY KEY (MAPB);

ALTER TABLE DDIEMPB
ADD CONSTRAINT ddiempb_pk PRIMARY KEY (MAPB, DIADIEM);

ALTER TABLE DEAN
ADD CONSTRAINT dean_pk PRIMARY KEY (MADA);

ALTER TABLE THANNHAN
ADD CONSTRAINT thannhan_pk PRIMARY KEY (MANV, TENTN);

ALTER TABLE PHANCONG
ADD CONSTRAINT phancong_pk PRIMARY KEY (MANV, MADA);

-- b. Tạo khóa ngoại

ALTER TABLE NHANVIEN 
ADD CONSTRAINT nhanvien_mapb_fk FOREIGN KEY (MAPB) REFERENCES PHONGBAN (MAPB);

ALTER TABLE PHONGBAN
ADD CONSTRAINT phongban_truongphong_fk FOREIGN KEY (TRUONGPHONG) REFERENCES NHANVIEN (MANV);

ALTER TABLE DDIEMPB
ADD CONSTRAINT ddiempb_mapb_fk FOREIGN KEY (MAPB) REFERENCES PHONGBAN (MAPB);

ALTER TABLE DEAN
ADD CONSTRAINT dean_mapb_fk FOREIGN KEY (MAPB) REFERENCES PHONGBAN (MAPB);

ALTER TABLE THANNHAN
ADD CONSTRAINT thannhan_manv_fk FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV);

ALTER TABLE PHANCONG
ADD CONSTRAINT phancong_manv_fk FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV),
	CONSTRAINT phancong_mada_fk FOREIGN KEY (MADA) REFERENCES DEAN (MADA);

-- 2.4. Nhập dữ liệu

